<a href="https://colab.research.google.com/github/Rijann12/Pythonquiz/blob/main/9_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Import


In [1]:
import numpy as np
#importing numpy as np

#BASIC


In [2]:
a=np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [4]:
b=np.array([[1,2,3],[3,4,9]])
print(b)

[[1 2 3]
 [3 4 9]]


In [5]:
a=np.array([1,2,3],dtype=complex)
print(a)


[1.+0.j 2.+0.j 3.+0.j]


#Attributes

In [6]:
a=np.array([[1,2,3],[3,4,5]])
a.shape

(2, 3)

In [8]:
a.shape=(3,2)
print(a)
print(a.shape)


[[1 2]
 [3 3]
 [4 5]]
(3, 2)


In [80]:
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [17]:
a.ndim

1

In [13]:
a.shape=(12,2)
print(a)
print(a.ndim)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
2


In [18]:
a.shape=(4,3,2)
print(a)
print(a.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
3


In [19]:
x=np.array([1,2,3,4],dtype=np.int8)
print(x.itemsize)

1


In [20]:
x=np.array([1,2,3,4],dtype=np.float32)
print(x.itemsize)


4


#Array Creation


In [21]:
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [23]:
x=np.zeros((2,2))
print(x)

[[0. 0.]
 [0. 0.]]


In [27]:
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [28]:
a=np.ones((3,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#ASARRAY


In [31]:
a=[1,2,3,4]
print(type(a))
x=np.asarray(a)
print(type(x))

<class 'list'>
<class 'numpy.ndarray'>


In [32]:
a=(1,2,3)
print(type(a))
x=np.asarray(a)
print(type(x))

<class 'tuple'>
<class 'numpy.ndarray'>


In [33]:
a=[(1,2,3),(33,44,55)]
print(type(a))
x=np.asarray(a)
print(type(x))
print(x)

<class 'list'>
<class 'numpy.ndarray'>
[[ 1  2  3]
 [33 44 55]]


In [34]:
x={1:55,2:66}
print(x)
print(type(x))

{1: 55, 2: 66}
<class 'dict'>


In [35]:
y=np.asarray(x)
print(type(y))
print(y)

<class 'numpy.ndarray'>
{1: 55, 2: 66}


#Numpy asrray from multiple ranges


In [36]:
x=np.arange(5)
print(x)

[0 1 2 3 4]


In [37]:
x=np.arange(5,50,5)
print(x)

[ 5 10 15 20 25 30 35 40 45]


In [40]:
x=np.linspace(5,50,5)
print(x)

[ 5.   16.25 27.5  38.75 50.  ]


#array indexing

In [42]:
a=np.array([[1,2,3,4,5],[7,8,9,10,11],[12,13,14,15,16]])
print(a)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]


In [47]:
a[-1,1:3]

array([13, 14])

In [48]:
print(a>2)

[[False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


Math

In [54]:
x=np.array(([12,13],[15,16]))
y=np.array(([2,3],[5,6]))



In [55]:
print(x)
print(y)

[[12 13]
 [15 16]]
[[2 3]
 [5 6]]


In [56]:
print(x+y)
print(np.add(x,y))

[[14 16]
 [20 22]]
[[14 16]
 [20 22]]


In [57]:
print(x-y)
print(np.subtract(x,y))


[[10 10]
 [10 10]]
[[10 10]
 [10 10]]


In [60]:
print(x*y)
print(np.multiply(x,y))
#individual multiplication garxa

[[24 39]
 [75 96]]
[[24 39]
 [75 96]]


In [58]:
np.sqrt(x)


array([[3.46410162, 3.60555128],
       [3.87298335, 4.        ]])

In [59]:
print(x.dot(y))
print(np.dot(x,y))

[[ 89 114]
 [110 141]]
[[ 89 114]
 [110 141]]


In [62]:
np.sum(x)

56

In [64]:
np.sum(x,axis=0)

array([27, 29])

In [65]:
np.sum(x,axis=1)

array([25, 31])

In [66]:
x.T

array([[12, 15],
       [13, 16]])

In [67]:
y=np.linalg.inv(x)
print(y)

[[-5.33333333  4.33333333]
 [ 5.         -4.        ]]


In [68]:
np.dot(x,y)
#dot le matrix multiplication garxa

array([[ 1.00000000e+00, -7.10542736e-15],
       [ 0.00000000e+00,  1.00000000e+00]])

#Broadcasting

In [69]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[8,5,2]])
y=np.array([1,0,1])


In [70]:
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [8, 5, 2]])

In [71]:
y

array([1, 0, 1])

In [72]:
np.dot(x,y)

array([ 4, 10, 16, 10])