<a href="https://colab.research.google.com/github/Rijann12/Python/blob/main/ProjectModelTrain.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Libraries

In [63]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Data Preprocessing

## Training Image Preprocessing

In [64]:
training_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/ProjectData/train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=64,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)



Found 40697 files belonging to 22 classes.


In [65]:
training_set
training_set = training_set.prefetch(buffer_size=tf.data.AUTOTUNE) # prefetch() helps in pieplining.So, one process runs in parallel(overlapping) with another process (like CPU loading and preparing next batch).
# while GPU is training on batch n,CPU is already preparing batch n+1 in background.Basically for faster training.

In [66]:
for x,y in training_set:
  print(x,x.shape)
  print(y,y.shape)
  break


tf.Tensor(
[[[[ 75.5   66.5   69.5 ]
   [ 69.5   60.5   63.5 ]
   [ 64.25  55.25  58.25]
   ...
   [ 87.5   79.5   77.5 ]
   [ 83.    75.    73.  ]
   [ 89.75  81.75  79.75]]

  [[ 70.    61.    64.  ]
   [ 62.75  53.75  56.75]
   [ 67.75  58.75  61.75]
   ...
   [ 86.25  78.25  76.25]
   [ 87.25  79.25  77.25]
   [ 88.5   80.5   78.5 ]]

  [[ 67.25  58.25  61.25]
   [ 60.25  51.25  54.25]
   [ 66.    57.    60.  ]
   ...
   [ 84.75  76.75  74.75]
   [ 88.75  80.75  78.75]
   [ 91.    83.    81.  ]]

  ...

  [[142.25 133.25 136.25]
   [145.5  136.5  139.5 ]
   [153.5  144.5  147.5 ]
   ...
   [187.   182.   179.  ]
   [186.5  181.5  178.5 ]
   [181.   176.   173.  ]]

  [[130.5  121.5  124.5 ]
   [132.5  123.5  126.5 ]
   [153.5  144.5  147.5 ]
   ...
   [184.5  179.5  176.5 ]
   [177.5  172.5  169.5 ]
   [193.75 188.75 185.75]]

  [[127.25 118.25 121.25]
   [141.75 132.75 135.75]
   [145.25 136.25 139.25]
   ...
   [190.5  185.5  182.5 ]
   [184.25 179.25 176.25]
   [185.5  180.5  17

## Validation Image Preprocessing


In [67]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/ProjectData/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=64,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 10188 files belonging to 22 classes.


In [68]:
validation_set
validation_set = validation_set.prefetch(buffer_size=tf.data.AUTOTUNE)


## To avoid Overshooting
1. Choose small learning rate default 0.001 we are taking 0.0001
2. There may be chance of Underfitting, so incresase number of neuron
3. Add more Convolutional layer to extract more feature from images there may  be possibility that the model uanle to captutre relevant feature or model is confusing due to lack of feature so feed with more feature

# Building Model

In [69]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

In [70]:
model = Sequential()

In [71]:
#Building Convolutional Layer
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu',input_shape=(128,128,3)))
model.add(Conv2D(filters=32, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))


In [72]:
model.add(Conv2D(filters=64, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=64, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))


In [73]:
model.add(Conv2D(filters=128, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=128, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))


In [74]:
model.add(Conv2D(filters=256, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=256, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [75]:
model.add(Conv2D(filters=512, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=512, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [76]:
model.add(Dropout(0.25))

In [77]:
model.add(Flatten())

In [78]:
model.add(Dense(units=1500, activation='relu'))

In [79]:
model.add(Dropout(0.4))

In [81]:
# Output layer
model.add(Dense(units=22, activation='softmax'))#units are the no of class present in the dataset

#Compiling the model

In [82]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001), loss='categorical_crossentropy',metrics=['accuracy'] )


In [83]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_30 (Conv2D)              │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_31 (Conv2D)              │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_15 (MaxPooling2D) │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_32 (Conv2D)              │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_33 (Conv2D)              │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_16 (MaxPooling2D) │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_34 (Conv2D)              │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_35 (Conv2D)              │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_17 (MaxPooling2D) │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_36 (Conv2D)              │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_37 (Conv2D)              │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_18 (MaxPooling2D) │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_38 (Conv2D)              │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_39 (Conv2D)              │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_19 (MaxPooling2D) │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 23)             │        34,523 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 22)             │           528 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,820,775 (29.83 MB)

 Trainable params: 7,820,775 (29.83 MB)

 Non-trainable params: 0 (0.00 B)

#Model Training

In [84]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
training_history = model.fit(
    training_set,
    validation_data=validation_set,
    epochs=14,
    callbacks=[early_stop]
)

Epoch 1/14
 25/636 ━━━━━━━━━━━━━━━━━━━━ 1:05:39 6s/step - accuracy: 0.0367 - loss: 3.0986

KeyboardInterrupt: 

In [ ]:
#training_history = model.fit(x=training_set, validation_data=validation_set, epochs=9
                             )

## Model Evaluation

In [ ]:
# Model Evaluation on Training Set
train_loss, train_acc = model.evaluate(training_set)

In [ ]:
print("Train loss:",train_loss, "Train Accuracy:",train_acc)

In [ ]:
# Model validation Set
val_loss, val_acc = model.evaluate(validation_set)

In [ ]:
print("Validation loss:", val_loss, "Validation accuracy:", val_acc)

# Saving model

In [ ]:
model.save("trained_model.h5")

In [ ]:
# To save this file we have used 'keras' format as it compresses the file size whereas '.h5' format takes up more file size
model.save("trained_model.keras")


In [ ]:
training_history.history
# validation accuracy tara validation garesi garne
#training_history.history(val_accuracy)

In [ ]:
# Recording the histroy in json
# We have saved this training history in 'json' for future use of the data or perform data visualization as we can just read this history
# Also for the future use of the this model as we cannot run the model again and again if we need it for future
import json
with open("training_hist.json","w") as f:
  json.dump(training_history.history,f);

print("Model & training history saved.")

In [ ]:
# model.evaluate() computes loss and accuracy metrics on given dataset
# It checks for overfittting, if training accuracy higher than validation accuracy, model might be overfitting.
train_loss, train_acc = model.evaluate(training_set)
print(f"Train Loss: {train_loss:.4f}, Accuracy: {train_acc:.4f}")

val_loss, val_acc = model.evaluate(validation_set)
print(f"Valid Loss: {val_loss:.4f}, Accuracy: {val_acc:.4f}")


# Accuracy Visualization

In [ ]:
epochs = range(1, len(training_history.history['accuracy']) + 1)
plt.figure(figsize=(8, 5))
plt.plot(epochs, training_history.history['accuracy'], 'r', label='Train Acc')
plt.plot(epochs, training_history.history['val_accuracy'], 'b', label='Val Acc')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Training & Validation Accuracy')
plt.legend()
plt.show()


In [ ]:
# epochs = { i for in range(1,1)}
# plt.plot(epochs, training_history.history ['accuracy'], color= 'red', label='Training Accuracy')
# plt.plot(epochs, training_history.history ['val_accuracy'], color= 'blue', label='Vlaidation Accuracy')
# plt.xlabel("No. of epochs")
# plt.ylabel("Accuracy Result")
# plt.title("Visualization Accuracy Result")
# plt.legend()
# plt.show()

# Some other matrices for model evaluation

In [ ]:
  class_name = validation_set.class_names
  class_name

In [ ]:
test_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/ProjectData/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=False,# Setting shuffle as False for the testing passes the folders from validation folder sequentially from starting to bottom
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)
test_set = test_set.prefetch(tf.data.AUTOTUNE)


In [ ]:
y_pred = model.predict(test_set)
y_pred, y_pred.shape

In [ ]:
predicted_categories = tf.argmax(y_pred,axis=1) # this goes to inside y_pred and extract the maximum value and return the index of that max value and axis=1 means it return the index in column wise

In [ ]:
predicted_categories

In [ ]:
# true_categories = tf.concat( [y for x,y in test_set], axis=0)
# true_categories
true_categories = tf.concat([labels for _, labels in test_set], axis=0)
true_categories = tf.argmax(true_categories, axis=1)
true_categories

In [ ]:
# Y_true=predicted_categories = tf.argmax(y_pred,axis=1)
# Y_true
Y_true = true_categories
Y_pred = predicted_categories

In [ ]:
# Calcualate Precision recall
# Precision measures the precentage made by the model that are correct.
# Recall measures the percenatage of the relevant data points that were correctly identified by the model.


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
#print(classification_report(Y_true, predicted_categories target_names=class_name))
print(classification_report(Y_true.numpy(), Y_pred.numpy(), target_names=class_name))


In [ ]:
# F-1 score calculation, perfect model have F-1 score of 1.
# cm = confusion_matrix(Y_true, predicted_categories)
cm = confusion_matrix(Y_true.numpy(), Y_pred.numpy())
cm.shape()

# Visualization of Confusion matrix

In [ ]:
#sns.heatmap(cm)
plt.figure(figsize=(40, 40))
sns.heatmap(cm, annot=True, annot_kws={'size':10})
plt.xlabel("Predicted Class", fontsize=20)
plt.ylabel("Actual Class", fontsize=20)
plt.title("Plant Disease Confusion Matrix", fontsize=20)
plt.show()
# the result is saying it is confusion matix and the diagonal element is saying that it belongs to that class and actually it belings to that class
# we can tune this model by adjusting filters, improving no. of nuerons, adjusting loss function